name: RLC
tagline: REINFORCEMENT <br> LEARNING <br> CONFERENCE
date: August 9-12 2024
citation_date: August 2024
proceedings_title: Proceedings of the First Reinforcement Conference
analytics: UA-
logo:
  image: static/images/tmp_logo.jpg
  width: 150px
  height: auto
# uncomment the following line to show the site title next to the logo image
# site_title: MiniConf
page_title:
  prefix: 'MiniConf 2020'
  separator: ': '
background_image: static/images/umass_amherst.jpg
organization: MiniConf Organization Committee

# Remove or change to your chat server.
chat_server: miniconf.sloppy.zone
default_presentation_id: 38922815
default_poster_pdf: /static/images/GLTR_poster.pdf


# Configuration for auth
#Test user
#user: miniconf@miniconf.com
#pass: mIniconf1_

use_auth0:
auth0_client_id : JIdr6wi0z27LyLgwkJF0fpk700aj7MNH
auth0_domain : miniconf.auth0.com

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
